<a href="https://colab.research.google.com/github/fatehtariq/Fashion-MNIST-Classifier/blob/main/Fashion_MNIST_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fashion MNIST Classifier

**Libraries**

In [78]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from keras.layers.normalization import BatchNormalization
import pandas as pd
from tensorflow.math import confusion_matrix
from sklearn.metrics import plot_confusion_matrix

**Loading Dataset**

In [ ]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [ ]:
print("x_train shape (Training Images):", x_train.shape, "y_train shape (Training Labels):", y_train.shape)

x_train shape (Training Images): (60000, 28, 28) y_train shape (Training Labels): (60000,)


**Preprocessing Data**

In [ ]:
W, H = 28, 28
x_train = x_train.reshape(x_train.shape[0], W, H, 1)
x_test = x_test.reshape(x_test.shape[0], W, H, 1)

x_train.shape

(60000, 28, 28, 1)

**Model**

In [ ]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Dropout, Flatten, Activation

Model with Categorical Cross Entropy

In [ ]:
model1 = tf.keras.Sequential()

model1.add(Conv2D(filters=8, kernel_size=5, padding='same', activation='relu', input_shape=(28,28,1)))          
model1.add(MaxPooling2D(pool_size=2))
model1.add(Dropout(0.3))

model1.add(Conv2D(filters=32, kernel_size=7, activation='relu', input_shape=(8,8,1)))              
model1.add(MaxPooling2D(pool_size=1))
model1.add(Dropout(0.3))

model1.add(Conv2D(filters=64, kernel_size=5,activation='relu', input_shape=(4,4,1)))             
model1.add(MaxPooling2D(pool_size=1))
model1.add(Dropout(0.3))

model1.add(Conv2D(128, (3, 3),activation='relu', input_shape=(2,2,1)))              
model1.add(MaxPooling2D(pool_size=1))
model1.add(Dropout(0.3))

model1.add(Flatten())

model1.add(Dense(512))                                      
model1.add(Activation('relu'))
model1.add(Dropout(0.3))

model1.add(Dense(128))                                      
model1.add(Activation('relu'))
model1.add(Dropout(0.3))

model1.add(Dense(10))                                     
model1.add(Activation('Softmax'))

model1.summary()

Model: "sequential_22"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_85 (Conv2D)           (None, 28, 28, 8)         208       
_________________________________________________________________
max_pooling2d_82 (MaxPooling (None, 14, 14, 8)         0         
_________________________________________________________________
dropout_118 (Dropout)        (None, 14, 14, 8)         0         
_________________________________________________________________
conv2d_86 (Conv2D)           (None, 8, 8, 32)          12576     
_________________________________________________________________
max_pooling2d_83 (MaxPooling (None, 8, 8, 32)          0         
_________________________________________________________________
dropout_119 (Dropout)        (None, 8, 8, 32)          0         
_________________________________________________________________
conv2d_87 (Conv2D)           (None, 4, 4, 64)        

Model with Mean Squared Error

In [59]:
model2 = tf.keras.Sequential()

model2.add(Conv2D(filters=8, kernel_size=5, padding='same', activation='relu', input_shape=(28,28,1)))          
model2.add(MaxPooling2D(pool_size=2))
model2.add(Dropout(0.3))

model2.add(Conv2D(filters=32, kernel_size=7, activation='relu', input_shape=(8,8,1)))              
model2.add(MaxPooling2D(pool_size=1))
model2.add(Dropout(0.3))

model2.add(Conv2D(filters=64, kernel_size=5,activation='relu', input_shape=(4,4,1)))             
model2.add(MaxPooling2D(pool_size=1))
model2.add(Dropout(0.3))

model2.add(Conv2D(128, (3, 3),activation='relu', input_shape=(2,2,1)))              
model2.add(MaxPooling2D(pool_size=1))
model2.add(Dropout(0.3))

model2.add(Flatten())

model2.add(Dense(512))                                      
model2.add(Activation('relu'))
model2.add(Dropout(0.3))

model2.add(Dense(128))                                      
model2.add(Activation('relu'))
model2.add(Dropout(0.3))

model2.add(Dense(10))                                     
model2.add(Activation('Softmax'))

model2.summary()

Model: "sequential_23"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_89 (Conv2D)           (None, 28, 28, 8)         208       
_________________________________________________________________
max_pooling2d_86 (MaxPooling (None, 14, 14, 8)         0         
_________________________________________________________________
dropout_124 (Dropout)        (None, 14, 14, 8)         0         
_________________________________________________________________
conv2d_90 (Conv2D)           (None, 8, 8, 32)          12576     
_________________________________________________________________
max_pooling2d_87 (MaxPooling (None, 8, 8, 32)          0         
_________________________________________________________________
dropout_125 (Dropout)        (None, 8, 8, 32)          0         
_________________________________________________________________
conv2d_91 (Conv2D)           (None, 4, 4, 64)        

**Compiling and Training the Model with Categorical Cross Entropy**

In [60]:
BATCH_SIZE=1000
EPOCHS = 50
model1.compile(loss='sparse_categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [61]:
%time history = model1.fit(x_train, y_train, epochs=EPOCHS, batch_size=BATCH_SIZE, validation_split=0.2, verbose=1)

Epoch 1/50
48/48 [==============================] - 3s 49ms/step - loss: 2.3018 - accuracy: 0.1011 - val_loss: 2.2294 - val_accuracy: 0.1877
Epoch 2/50
48/48 [==============================] - 2s 42ms/step - loss: 1.6864 - accuracy: 0.3297 - val_loss: 0.6483 - val_accuracy: 0.7298
Epoch 3/50
48/48 [==============================] - 2s 42ms/step - loss: 0.5524 - accuracy: 0.7969 - val_loss: 0.3369 - val_accuracy: 0.8772
Epoch 4/50
48/48 [==============================] - 2s 42ms/step - loss: 0.3678 - accuracy: 0.8679 - val_loss: 0.2825 - val_accuracy: 0.9000
Epoch 5/50
48/48 [==============================] - 2s 42ms/step - loss: 0.3165 - accuracy: 0.8865 - val_loss: 0.2656 - val_accuracy: 0.9028
Epoch 6/50
48/48 [==============================] - 2s 42ms/step - loss: 0.3036 - accuracy: 0.8903 - val_loss: 0.2714 - val_accuracy: 0.9019
Epoch 7/50
48/48 [==============================] - 2s 43ms/step - loss: 0.2946 - accuracy: 0.8925 - val_loss: 0.2616 - val_accuracy: 0.9027
Epoch 8/50
48

In [62]:
train_loss, train_accuracy = model1.evaluate(x_train, y_train, batch_size=BATCH_SIZE)
train_accuracy

60/60 [==============================] - 1s 12ms/step - loss: 0.1657 - accuracy: 0.9374


0.9373999834060669

In [63]:
test_loss, test_accuracy = model1.evaluate(x_test, y_test, batch_size=BATCH_SIZE)
test_accuracy

10/10 [==============================] - 0s 12ms/step - loss: 0.2642 - accuracy: 0.9100


0.9100000262260437

**Compiling and Training the Model with Mean Square Error**

In [64]:
BATCH_SIZE=1000
EPOCHS = 50
model2.compile(loss=tf.keras.losses.mean_squared_error,
             optimizer='adam',
             metrics=['accuracy'])

In [65]:
%time history = model2.fit(x_train, y_train, epochs=EPOCHS, batch_size=BATCH_SIZE, validation_split=0.2, verbose=1)

Epoch 1/50
48/48 [==============================] - 3s 48ms/step - loss: 27.6996 - accuracy: 0.1052 - val_loss: 27.3250 - val_accuracy: 0.0959
Epoch 2/50
48/48 [==============================] - 2s 42ms/step - loss: 27.6813 - accuracy: 0.0955 - val_loss: 27.3250 - val_accuracy: 0.0996
Epoch 3/50
48/48 [==============================] - 2s 42ms/step - loss: 27.6813 - accuracy: 0.0791 - val_loss: 27.3250 - val_accuracy: 0.0993
Epoch 4/50
48/48 [==============================] - 2s 41ms/step - loss: 27.6813 - accuracy: 0.0765 - val_loss: 27.3250 - val_accuracy: 0.1001
Epoch 5/50
48/48 [==============================] - 2s 41ms/step - loss: 27.6813 - accuracy: 0.0732 - val_loss: 27.3250 - val_accuracy: 0.1002
Epoch 6/50
48/48 [==============================] - 2s 41ms/step - loss: 27.6813 - accuracy: 0.0733 - val_loss: 27.3250 - val_accuracy: 0.0985
Epoch 7/50
48/48 [==============================] - 2s 41ms/step - loss: 27.6813 - accuracy: 0.0784 - val_loss: 27.3250 - val_accuracy: 0.0983

In [66]:
train_loss, train_accuracy = model2.evaluate(x_train, y_train, batch_size=BATCH_SIZE)
train_accuracy

60/60 [==============================] - 1s 11ms/step - loss: 27.6100 - accuracy: 0.1000


0.10000000149011612

In [67]:
test_loss, test_accuracy = model2.evaluate(x_test, y_test, batch_size=BATCH_SIZE)
test_accuracy

10/10 [==============================] - 0s 13ms/step - loss: 27.6100 - accuracy: 0.1000


0.10000000149011612

In [70]:
predictions1 = model1.predict(x_test)

In [71]:
predictions1

array([[7.56357321e-25, 2.40299943e-26, 7.09197313e-24, ...,
        2.38157936e-05, 6.74241799e-17, 9.99976158e-01],
       [4.61840983e-07, 1.22142612e-20, 9.99795854e-01, ...,
        9.66274318e-31, 7.57599550e-14, 2.51308354e-30],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [9.48029503e-20, 0.00000000e+00, 4.00741108e-30, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.35550410e-29, 1.00000000e+00, 1.53393435e-33, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.42030839e-08, 6.36963052e-11, 4.63495997e-09, ...,
        5.72378635e-02, 1.52920809e-04, 7.71280611e-05]], dtype=float32)

In [86]:
yhat_classes = model1.predict_classes(x_test, verbose=0)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


**Confusion Matrix for Categorical Cross Entropy**

In [89]:
matrix = confusion_matrix(y_test, yhat_classes)
print(matrix)

tf.Tensor(
[[877   1  15  13   4   1  84   0   5   0]
 [  2 984   0  11   1   0   2   0   0   0]
 [ 17   0 824   7  74   0  77   0   1   0]
 [  9   6   6 925  35   0  19   0   0   0]
 [  1   1  35  26 865   0  72   0   0   0]
 [  0   0   0   0   0 972   0  23   0   5]
 [108   1  45  31  69   0 741   0   5   0]
 [  0   0   0   0   0   5   0 985   0  10]
 [  4   1   1   2   3   2   4   3 980   0]
 [  0   0   0   0   0   6   0  47   0 947]], shape=(10, 10), dtype=int32)


**Confusion Matrix for Mean Squared Error**

In [90]:
yhat_classes2 = model2.predict_classes(x_test, verbose=0)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [92]:
matrix = confusion_matrix(y_test, yhat_classes2)
print(matrix)

tf.Tensor(
[[   0    0    0    0    0    0 1000    0    0    0]
 [   0    0    0    0    0    0 1000    0    0    0]
 [   0    0    0    0    0    0 1000    0    0    0]
 [   0    0    0    0    0    0 1000    0    0    0]
 [   0    0    0    0    0    0 1000    0    0    0]
 [   0    0    0    0    0    0 1000    0    0    0]
 [   0    0    0    0    0    0 1000    0    0    0]
 [   0    0    0    0    0    0 1000    0    0    0]
 [   0    0    0    0    0    0 1000    0    0    0]
 [   0    0    0    0    0    0 1000    0    0    0]], shape=(10, 10), dtype=int32)
